theme: jekyll-theme-cayman
title: Portfolio Yacine Yefsah
description: Bienvenue sur mon portfolio professionnel. Spécialisé en **Statistique Appliquée** et **Analyse de Données**, je combine rigueur mathématique et outils informatiques pour valoriser la donnée.
